media:
  input: public/media
  output: /media

content:
  - name: themes
    label: Themes
    type: list
    path: 'themes.tsx'
    fields:
      - name: id
        label: ID
        type: string
        required: true
        description: "Lowercase identifier for URLs. Examples: 'stress', 'zelfvertrouwen', 'burn-out', 'depressie', 'perfectionisme', 'relaties'"
      - name: name
        label: Name
        type: string
        required: true
        description: "Short display name. Examples: 'Stress', 'Zelfvertrouwen', 'Burn-out', 'Depressie', 'Perfectionisme', 'Relaties'"
      - name: title
        label: Full Title
        type: string
        required: true
        description: "Complete theme title. Examples: 'Stress & Draagkracht', 'Zelfvertrouwen & Zelfbeeld', 'Burn-out & Preventie', 'Depressie & Somberheid', 'Perfectionisme & Faalangst', 'Relaties'"
      - name: icon
        label: Icon Name
        type: string
        required: true
        description: "Icon from Lucide React (https://lucide.dev/icons). Use exact icon name. Examples: 'Timer', 'Sparkles', 'PowerOff', 'CloudRain', 'Target', 'Heart'. The icon component will be imported automatically."
      - name: question
        label: Question
        type: string
        required: true
        description: "Short question shown on card hover. Examples: 'Hoe vind ik rust in de chaos?', 'Waarom ben ik zo kritisch op mezelf?', 'Wanneer ben ik goed genoeg?', 'Waarom voel ik me zo onzeker in relaties?'"
      - name: description
        label: Description
        type: text
        required: true
        description: "Full explanation shown on Voor Wie page. Describe the theme, what issues it addresses, and how coaching can help."

  - name: home
    label: Home Page
    type: file
    path: 'public/content/pages/home.md'
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: subtitle
        label: Subtitle
        type: text
      - name: heroImage
        label: Hero Image
        type: string
      - name: heroImageAlt
        label: Hero Image Alt Text
        type: string
      - name: ctaText
        label: CTA Button Text
        type: string
      - name: ctaLink
        label: CTA Button Link
        type: string
      - name: sectionTitle
        label: Section Title
        type: string
      - name: sectionText
        label: Section Text
        type: text
      - name: themesTitle
        label: Themes Title
        type: string
  
  - name: about
    label: About Page
    type: file
    path: 'public/content/pages/about.md'
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: quote
        label: Quote
        type: text
      - name: image
        label: Image
        type: string
      - name: imageAlt
        label: Image Alt Text
        type: string
      - name: approachTitle
        label: Approach Title
        type: string
      - name: approachText
        label: Approach Text
        type: text
      - name: educationTitle
        label: Education Title
        type: string
      - name: educationItems
        label: Education Items
        type: list
        fields:
          - name: item
            label: Item
            type: string
  
  - name: contact
    label: Contact Page
    type: file
    path: 'public/content/pages/contact.md'
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: subtitle
        label: Subtitle
        type: text
      - name: locationTitle
        label: Location Title
        type: string
      - name: locationText
        label: Location Text
        type: string
      - name: emailTitle
        label: Email Title
        type: string
      - name: emailAddress
        label: Email Address
        type: string
  
  - name: method
    label: Method Page
    type: file
    path: 'public/content/pages/method.md'
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: methodTitle
        label: Method Title
        type: string
      - name: steps
        label: Steps
        type: list
        fields:
          - name: number
            label: Number
            type: number
          - name: title
            label: Step Title
            type: string
          - name: description
            label: Step Description
            type: text
      - name: ctaText
        label: CTA Text
        type: string
      - name: ctaLink
        label: CTA Link
        type: string
  
  - name: rates
    label: Rates Page
    type: file
    path: 'public/content/pages/rates.md'
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: introSessionTitle
        label: Intro Session Title
        type: string
      - name: introSessionDescription
        label: Intro Session Description
        type: string
      - name: introSessionPrice
        label: Intro Session Price
        type: string
      - name: coachingSessionTitle
        label: Coaching Session Title
        type: string
      - name: coachingSessionDescription
        label: Coaching Session Description
        type: string
      - name: coachingSessionPrice
        label: Coaching Session Price
        type: string
      - name: practicalInfoTitle
        label: Practical Info Title
        type: string
      - name: compensationTitle
        label: Compensation Title
        type: string
      - name: compensationText
        label: Compensation Text
        type: text
      - name: paymentTitle
        label: Payment Title
        type: string
      - name: paymentText
        label: Payment Text
        type: text
      - name: cancellationTitle
        label: Cancellation Title
        type: string
      - name: cancellationText
        label: Cancellation Text
        type: text
      - name: ctaText
        label: CTA Text
        type: string
      - name: ctaLink
        label: CTA Link
        type: string
  
  - name: kennismakingsgesprek
    label: Kennismakingsgesprek Page
    type: file
    path: 'public/content/pages/kennismakingsgesprek.md'
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: subtitle
        label: Subtitle
        type: text
      - name: formNameLabel
        label: Form Name Label
        type: string
      - name: formEmailLabel
        label: Form Email Label
        type: string
      - name: formTopicLabel
        label: Form Topic Label
        type: string
      - name: formSubmitText
        label: Form Submit Text
        type: string
  
  - name: forwhom
    label: For Whom Page
    type: file
    path: 'public/content/pages/forwhom.md'
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: subtitle
        label: Subtitle
        type: text
      - name: closingTitle
        label: Closing Title
        type: string
      - name: closingText
        label: Closing Text
        type: text
      - name: ctaText
        label: CTA Text
        type: string
      - name: ctaLink
        label: CTA Link
        type: string
